# Azure DevOps Pipeline for Sherlock Holmes AI
trigger:
  branches:
    include:
    - main
    - develop

variables:
  azureServiceConnectionId: 'your-service-connection-id'
  webAppName: 'sherlock-holmes-ai'
  resourceGroupName: 'sherlock-holmes-rg'
  containerRegistryName: 'sherlockholmesacr'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildJob
    displayName: Build Job
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    - task: Docker@2
      displayName: Login to Azure Container Registry
      inputs:
        command: 'login'
        containerRegistry: '$(azureServiceConnectionId)'
    
    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        command: 'buildAndPush'
        repository: 'sherlock-holmes-ai'
        dockerfile: '**/Dockerfile'
        containerRegistry: '$(azureServiceConnectionId)'
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  displayName: Deploy to Azure App Service
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - deployment: DeployJob
    displayName: Deploy Job
    environment: 'production'
    pool:
      vmImage: 'ubuntu-latest'
    
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebAppContainer@1
            displayName: Deploy to Azure App Service
            inputs:
              azureSubscription: '$(azureServiceConnectionId)'
              appName: '$(webAppName)'
              containers: '$(containerRegistryName).azurecr.io/sherlock-holmes-ai:$(Build.BuildId)'
              appSettings: |
                -GOOGLE_API_KEY "$(GOOGLE_API_KEY)"
                -SECRET_KEY "$(SECRET_KEY)"
                -FLASK_ENV "production"
                -CHROMA_DB_PATH "/tmp/chroma_db"
                -LOG_LEVEL "INFO"
